workspace = { members = ["easy/a-very-big-sum", "easy/compare-the-triplets", "easy/diagonal-difference", "easy/simple-array-sum", "easy/solve-me-first", "medium/bear-and-steady-gene", "medium/bigger-is-greater", "medium/climbing-the-leaderboard", "medium/coin-change"] }

resolver = "2"
